name: Pipeline
on:
  push:
  schedule:
  - cron: '0 1 * * 1' # Every Monday at 1AM UTC
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop
  tests:
    uses: Invoca/ruby-test-matrix-workflow/.github/workflows/ruby-test-matrix.yml@main
